spring:
  profiles:
    active: many_to_one
  liquibase:
    contexts: ${spring.profiles.active}
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    username: admin
    url: jdbc:postgresql://localhost:5432/${spring.profiles.active}
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace