version: '3.8'
services:
  java-persistence:
    image: postgres:latest
    container_name: entity-relationship
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: many2one,one2many,one2one,single_table
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

volumes:
  postgres-data: