version: '3.8'
services:
  java-persistence:
    image: postgres:latest
    container_name: jpa-inheritance
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: single_table,joined,table_per_class,mapped_superclass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

volumes:
  postgres-data: