log:
  level: trace

logging:
  level:
    liquibase: off
    # shows transactions info

    org:
      springframework:
        data.jpa: ${log.level}
        transaction: ${log.level}
      hibernate:
        orm.idgen.factory: off
        orm.results.graph.AST: off
        type.BasicTypeRegistry: off
        boot.registry.selector.internal.StrategySelectorImpl: off
        service.internal.AbstractServiceRegistryImpl: off
        engine.internal.Cascade: off
        engine.jdbc.internal.JdbcCoordinatorImpl: off
        persister.entity.AbstractPropertyMapping: off

#    org:
#      springframework:
#        data.jpa: ${log.level}
#        transaction.interceptor: ${log.level}
#      hibernate:
#        resource:
#          jdbc.internal.AbstractLogicalConnectionImplementor: ${log.level}
#          transaction.internal.TransactionCoordinatorBuilderInitiator: ${log.level}
#        engine:
#          internal: ${log.level}
#          jdbc: ${log.level}
#          jdbc.env.internal.NormalizingIdentifierHelperImpl: off
#          transaction: ${log.level}
#          query: ${log.level}
#        internal.util.type: ${log.level}
#        event.internal: ${log.level}
#        stat: ${log.level}
#        persister: ${log.level}
#        SQL: ${log.level}
#        orm.jdbc.bind: ${log.level}
#        type.descriptor: ${log.level}
#        cache: ${log.level}