spring:
  profiles:
    active: single_table # must match the active profile specified in each Main
  liquibase:
    contexts: ${spring.profiles.active}
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    username: admin
    url: jdbc:postgresql://localhost:5432/${spring.profiles.active}
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
    open-in-view: false


  config:
    import: optional:classpath:application.yaml # Import logging configurations from common

