spring:
  profiles:
    active: joined # must match the active profile specified in each Main
  liquibase:
    contexts: ${spring.profiles.active}
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    username: admin
    url: jdbc:postgresql://localhost:5432/${spring.profiles.active}
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

log:
  level: trace

logging:
  level:
    liquibase: info
    # shows transactions info

    org:
      springframework:
        data.jpa: ${log.level}
        transaction.interceptor: ${log.level}
      hibernate:
        resource:
          jdbc.internal.AbstractLogicalConnectionImplementor: ${log.level}
          transaction.internal.TransactionCoordinatorBuilderInitiator: ${log.level}
        engine:
          internal: ${log.level}
          jdbc: ${log.level}
          jdbc.env.internal.NormalizingIdentifierHelperImpl: off
          transaction: ${log.level}
          query: ${log.level}
        internal.util.type: ${log.level}
        event.internal: ${log.level}
        stat: ${log.level}
        persister: ${log.level}
        SQL: ${log.level}
        orm.jdbc.bind: ${log.level}
        type.descriptor: ${log.level}
        cache: ${log.level}
